on:
  push:
    branches:
      - master

name: Bump

jobs:
  bump:
    name: Bump
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '(cargo-release)') }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: "${{ secrets.COMMIT_KEY }}"

      - name: Git config
        run: |
          git config --global user.name 'Beep Boop'
          git config --global user.email 'moustacheful@users.noreply.github.com'

      - name: Create tag
        run: |
          cargo install cargo-release@0.23.1
          cargo release version patch --no-confirm --no-verify --execute
          cargo release commit --no-confirm --no-verify --execute
          cargo release tag --no-confirm --no-verify --execute
          cargo release push --no-confirm --no-verify --execute
