on:
  push:
    branches:
      - master

name: Bump

jobs:
  bump:
    name: Bump
    runs-on: ubuntu-latest
    if: "${{ !startsWith(github.event.head_commit.message, 'chore: Release') }}"
    steps:
      - uses: actions/checkout@v3
        with:
          token: "${{ secrets.COMMIT_KEY }}"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Git config
        run: |
          git config --global user.name 'Beep Boop'
          git config --global user.email 'moustacheful@users.noreply.github.com'

      - name: Release
        run: |
          cargo login ${{ secrets.PUBLISH_KEY }}
          cargo install cargo-release@0.23.1
          cargo release patch --no-confirm --no-verify --execute
